naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

groq:
  api-key: ${GROQ_API_KEY}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

server:
  tomcat:
    max-http-post-size: 10485760

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    basic:
      enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  security:
    enabled: false  # Spring Boot 2.0 이전용

logging:
  level:
    com.kitcha.article: DEBUG  # 로그 레벨 설정 (DEBUG로 변경)

app:
  test-message: "Cloud Bus 테스트 - 2025-03-30 20:66"
