naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

groq:
  api-key: ${GROQ_API_KEY}

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${ARTICLE_HOSTNAME}
    nonSecurePort: 80
    nonSecurePortEnabled: true
    instance-id: ${HOSTNAME}:${spring.application.name}:8080
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://54.215.85.146:8761/eureka/

server:
  tomcat:
    max-http-post-size: 10485760

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
