naver:
  client-id: F1hfeY_3SiHYWER4hcFy
  client-secret: uEw49fcQyu

groq:
  api-key: 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

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://54.215.85.146:8761/eureka/

server:
  tomcat:
    max-http-post-size: 10485760

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
