naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

groq:
  api-key: ${GROQ_API_KEY}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

server:
  tomcat:
    max-http-post-size: 10485760

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.kitcha.article: DEBUG  # 원래 INFO였다면 DEBUG로 변경

app:
  test-message: "Cloud Bus 테스트 성공 - 2025-03-29 12:00"