spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://kitchadb.cnqc2iqcsmsn.us-west-1.rds.amazonaws.com:3306/kitcha?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul"
      username: kitcha
      password: Corenova
      maximum-pool-size: 10      # ✅ 커넥션 풀 최대 수
      minimum-idle: 5            # 최소 유지 커넥션 수
      idle-timeout: 30000        # 유휴 커넥션 최대 유지 시간(ms)
      max-lifetime: 1800000      # 커넥션 최대 생존 시간(ms)
      connection-timeout: 30000  # 커넥션 가져올 때까지 최대 대기 시간(ms)
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8091

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${AUTH_HOSTNAME}
    nonSecurePort: 80
    nonSecurePortEnabled: true
    instance-id: ${HOSTNAME}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://54.215.85.146:8761/eureka/
